// src/Components/frameworks/FrameworksSection.tsx
import React, { useEffect, useRef, useState, useMemo } from "react";
import { gsap } from "gsap";
import { ScrollTrigger } from "gsap/ScrollTrigger";
import FrameworkCard, { type Framework } from "./FrameworkCard";
import "./FrameworksSection.css";

// Framework assets
import logoAstro from "@/assets/icons/astro.svg";
import logoNuxt from "@/assets/icons/nuxt.svg";
import logoVue from "@/assets/icons/vue.svg";
import logoAnalog from "@/assets/icons/analog.svg";
import logoPlaywright from "@/assets/icons/playwright.svg";
import logoMarko from "@/assets/icons/marko.svg";
import logoStorybook from "@/assets/icons/storybook.svg";
import logoQwik from "@/assets/icons/qwik.svg";
import logoVitest from "@/assets/icons/vitest.svg";
import logoRedwood from "@/assets/icons/redwood.svg";
import logoSolid from "@/assets/icons/solid.svg";
import logoAngular from "@/assets/icons/angular.svg";
import logoReact from "@/assets/icons/react.svg";
import logoRemix from "@/assets/icons/remix.svg";
import logoSvelte from "@/assets/icons/svelte.svg";
import logoLaravel from "@/assets/icons/laravel.svg";
import logoAdonis from "@/assets/icons/adonis.svg";
import logoEmber from "@/assets/icons/ember.svg";
import logoPreact from "@/assets/icons/preact.svg";
import logoHono from "@/assets/icons/hono.svg";
import logoPostman from "@/assets/icons/postman.svg";
import logoTypescript from "@/assets/icons/typescript.svg";
import logoMongodb from "@/assets/icons/mongodb.svg";
import logoJavascript from "@/assets/icons/javascript.svg";
import logoTailwind from "@/assets/icons/Tailwind_CSS.svg";
import logoNodejs from "@/assets/icons/nodejs.svg";

gsap.registerPlugin(ScrollTrigger);

/**
 * The frameworks and tools to display in this section.
 */
const frameworksData: Omit<Framework, "visible">[] = [
  {
    name: "TypeScript",
    logo: logoTypescript,
    color: "#3178c6",
    url: "https://www.typescriptlang.org/",
  },
  {
    name: "MongoDB",
    logo: logoMongodb,
    color: "#47a248",
    url: "https://www.mongodb.com/",
  },
  {
    name: "Vitest",
    logo: logoVitest,
    color: "#fac52b",
    url: "https://vitest.dev/",
  },
  {
    name: "React",
    logo: logoReact,
    color: "#00d6fd",
    url: "https://react.dev/",
  },
  {
    name: "Angular",
    logo: logoAngular,
    color: "#e03237",
    url: "https://angular.dev/",
  },
  {
    name: "Vue",
    logo: logoVue,
    color: "#40b782",
    url: "https://vuejs.org/",
  },
  {
    name: "Solid",
    logo: logoSolid,
    color: "#75b2df",
    url: "https://www.solidjs.com/",
  },
  {
    name: "Svelte",
    logo: logoSvelte,
    color: "#fd3e00",
    url: "https://svelte.dev/",
  },
  {
    name: "Preact",
    logo: logoPreact,
    color: "#673ab8",
    url: "https://preactjs.com/",
  },
  {
    name: "JavaScript",
    logo: logoJavascript,
    color: "#f7df1e",
    url: "https://developer.mozilla.org/en-US/docs/Web/JavaScript",
  },
  {
    name: "Astro",
    logo: logoAstro,
    color: "#FFFFFF",
    url: "https://astro.build",
  },
  {
    name: "Remix",
    logo: logoRemix,
    color: "#3991fd",
    url: "https://remix.run/",
  },
  {
    name: "Nuxt",
    logo: logoNuxt,
    color: "#00da81",
    url: "https://nuxt.com",
  },
  {
    name: "Qwik",
    logo: logoQwik,
    color: "#18b5f4",
    url: "https://qwik.dev/",
  },
  {
    name: "Redwood",
    logo: logoRedwood,
    color: "#be4622",
    url: "https://redwoodjs.com/",
  },
  {
    name: "Analog",
    logo: logoAnalog,
    color: "#c10f2e",
    url: "https://analogjs.org/",
  },
  {
    name: "Playwright",
    logo: logoPlaywright,
    color: "#d45247",
    url: "https://playwright.dev/",
  },
  {
    name: "Tailwind CSS",
    logo: logoTailwind,
    color: "#06b6d4",
    url: "https://tailwindcss.com/",
  },
  {
    name: "Node.js",
    logo: logoNodejs,
    color: "#339933",
    url: "https://nodejs.org/",
  },
  {
    name: "Storybook",
    logo: logoStorybook,
    color: "#fd4684",
    url: "https://storybook.js.org/",
  },
  {
    name: "Marko",
    logo: logoMarko,
    color: "#de2a87",
    url: "https://markojs.com/",
  },
  {
    name: "Laravel",
    logo: logoLaravel,
    color: "#eb4432",
    url: "https://laravel.com/",
  },
  {
    name: "AdonisJS",
    logo: logoAdonis,
    color: "#5a45ff",
    url: "https://adonisjs.com/",
  },
  {
    name: "EmberJS",
    logo: logoEmber,
    color: "#e04e39",
    url: "https://emberjs.com/",
  },
  {
    name: "Hono",
    logo: logoHono,
    color: "#ff5c13",
    url: "https://hono.dev/",
  },
  {
    name: "Postman",
    logo: logoPostman,
    color: "#ff6b35",
    url: "https://www.postman.com/",
  },
];

const FrameworksSection: React.FC = () => {
  const [screenWidth, setScreenWidth] = useState(1920);
  const [frameworks, setFrameworks] = useState<Framework[]>(
    frameworksData.map((framework) => ({ ...framework, visible: false }))
  );
  const timelineRef = useRef<gsap.core.Timeline | null>(null);
  const resizeTimeoutRef = useRef<ReturnType<typeof setTimeout> | null>(null);

  /**
   * When the resize event fires, update the screen width.
   */
  const handleResize = () => {
    setScreenWidth(window.innerWidth);
  };

  /**
   * Throttle the resize event handler.
   */
  const throttledResizeHandler = () => {
    if (resizeTimeoutRef.current === null) {
      resizeTimeoutRef.current = setTimeout(() => {
        handleResize();
        resizeTimeoutRef.current = null;
      }, 100);
    }
  };

  useEffect(() => {
    // Set the initial size of the screen
    handleResize();

    // Listen for resize events
    window.addEventListener("resize", throttledResizeHandler);

    // Initialize the GSAP timeline
    timelineRef.current = gsap.timeline({
      scrollTrigger: {
        trigger: "#frameworks-section",
        start: "top 70%",
        once: true,
      },
    });

    frameworks.forEach((_, index) => {
      timelineRef.current!.call(
        () => {
          setFrameworks((prev) =>
            prev.map((framework, i) =>
              i === index ? { ...framework, visible: true } : framework
            )
          );
        },
        [],
        index * 0.05
      );
    });

    return () => {
      // Deregister the throttled event handler
      window.removeEventListener("resize", throttledResizeHandler);

      // Clear any pending execution of the resize handler
      if (resizeTimeoutRef.current) {
        clearTimeout(resizeTimeoutRef.current);
        resizeTimeoutRef.current = null;
      }

      // Kill the GSAP timeline
      if (timelineRef.current) {
        timelineRef.current.kill();
        timelineRef.current = null;
      }
    };
  }, []);

  /**
   * How many total blocks (framework or empty) will fit in a single row?
   */
  const numBlocksPerRow = useMemo(() => {
    return Math.floor(screenWidth / (96 + 24));
  }, [screenWidth]);

  const paddedBlocksPerSide = useMemo(() => {
    if (screenWidth < 840) {
      return 0;
    }
    if (screenWidth < 1280) {
      return 1;
    }
    if (screenWidth < 1600) {
      return 2;
    }
    return Math.max(Math.floor((screenWidth - 840) / 280), 0);
  }, [screenWidth]);

  const numFrameworksPerRow = useMemo(
    () => numBlocksPerRow - paddedBlocksPerSide * 2,
    [numBlocksPerRow, paddedBlocksPerSide]
  );

  /**
   * How many rows do we need to display all the frameworks?
   */
  const numRows = useMemo(() => {
    return Math.ceil(frameworks.length / numFrameworksPerRow);
  }, [frameworks.length, numFrameworksPerRow]);

  /**
   * The indexes of the blocks on each row that support framework cards.
   */
  const centerIndexes = useMemo(() => {
    const firstRowsStartIndex = paddedBlocksPerSide;
    const frameworksPerFirstRows = numBlocksPerRow - 2 * paddedBlocksPerSide;
    const lastRowStartIndex =
      paddedBlocksPerSide +
      Math.floor(
        (frameworksPerFirstRows -
          (frameworks.length % frameworksPerFirstRows)) /
          2
      );

    return Array.from({ length: numRows + 1 }, (_, i) => {
      return i < numRows || frameworks.length % frameworksPerFirstRows === 0
        ? {
            start: firstRowsStartIndex,
            end: numBlocksPerRow - paddedBlocksPerSide,
          }
        : {
            start: lastRowStartIndex,
            end:
              lastRowStartIndex +
              (frameworks.length % frameworksPerFirstRows) +
              1,
          };
    });
  }, [numRows, numBlocksPerRow, paddedBlocksPerSide, frameworks.length]);

  /**
   * Generate CSS transformations for each row, to gracefully slide between horizontal positions.
   */
  const rowStyle = {
    transform: "translate3d(var(--row-offset), 0, 0)",
  };

  return (
    <section className="frameworks-section" id="frameworks-section">
      <h2>Powering your favorite frameworks and tools</h2>
      <div className="frameworks-container">
        {/* Top Row */}
        <div className="framework-row" style={rowStyle}>
          {Array.from({ length: numBlocksPerRow + 2 }, (_, index) => (
            <FrameworkCard key={`top-${index}`} />
          ))}
        </div>

        {/* Logo Rows */}
        {Array.from({ length: numRows }, (_, rowIndex) => (
          <div
            key={`row-${rowIndex}`}
            className="framework-row"
            style={rowStyle}
          >
            {Array.from({ length: numBlocksPerRow + 2 }, (_, columnIndex) => {
              const isInCenterRange =
                columnIndex - 1 >= centerIndexes[rowIndex + 1].start &&
                columnIndex - 1 < centerIndexes[rowIndex + 1].end;

              if (isInCenterRange) {
                const frameworkIndex =
                  rowIndex * numFrameworksPerRow +
                  (columnIndex - 1) -
                  centerIndexes[rowIndex + 1].start;

                return (
                  <FrameworkCard
                    key={`framework-${rowIndex}-${columnIndex}`}
                    framework={frameworks[frameworkIndex]}
                  />
                );
              } else {
                return (
                  <FrameworkCard key={`empty-${rowIndex}-${columnIndex}`} />
                );
              }
            })}
          </div>
        ))}

        {/* Bottom Row */}
        <div className="framework-row" style={rowStyle}>
          {Array.from({ length: numBlocksPerRow + 2 }, (_, index) => (
            <FrameworkCard key={`bottom-${index}`} />
          ))}
        </div>
      </div>
    </section>
  );
};

export default FrameworksSection;

// src/Components/frameworks/FrameworksSection.vue
<script setup lang="ts">
import { computed, ComputedRef, onMounted, onUnmounted, Ref, ref } from 'vue'
import FrameworkCard, { Framework } from './FrameworkCard.vue'
import { gsap } from 'gsap'
import { ScrollTrigger } from 'gsap/dist/ScrollTrigger'

gsap.registerPlugin(ScrollTrigger)

// Framework assets
import logoAstro from './image/astro.svg'
import logoNuxt from './image/nuxt.svg'
import logoVue from './image/vue.svg'
import logoAnalog from './image/analog.svg'
import logoPlaywright from './image/playwright.svg'
import logoMarko from './image/marko.svg'
import logoStorybook from './image/storybook.svg'
import logoQwik from './image/qwik.svg'
import logoVitest from './image/vitest.svg'
import logoRedwood from './image/redwood.svg'
import logoSolid from './image/solid.svg'
import logoAngular from './image/angular.svg'
import logoReact from './image/react.svg'
import logoRemix from './image/remix.svg'
import logoSvelte from './image/svelte.svg'
import logoLaravel from './image/laravel.svg'
import logoAdonis from './image/adonis.svg'
import logoEmber from './image/ember.svg'
import logoPreact from './image/preact.svg'
import logoHono from './image/hono.svg'

/**
 * The frameworks and tools to display in this section.
 */
const frameworks: Framework[] = [
  {
    name: 'Vitest',
    logo: logoVitest,
    color: '#fac52b',
    url: 'https://vitest.dev/',
    visible: ref(false),
  },
  {
    name: 'React',
    logo: logoReact,
    color: '#00d6fd',
    url: 'https://react.dev/',
    visible: ref(false),
  },
  {
    name: 'Angular',
    logo: logoAngular,
    color: '#e03237',
    url: 'https://angular.dev/',
    visible: ref(false),
  },
  {
    name: 'Vue',
    logo: logoVue,
    color: '#40b782',
    url: 'https://vuejs.org/',
    visible: ref(false),
  },
  {
    name: 'Solid',
    logo: logoSolid,
    color: '#75b2df',
    url: 'https://www.solidjs.com/',
    visible: ref(false),
  },
  {
    name: 'Svelte',
    logo: logoSvelte,
    color: '#fd3e00',
    url: 'https://svelte.dev/',
    visible: ref(false),
  },
  {
    name: 'Preact',
    logo: logoPreact,
    color: '#673ab8',
    url: 'https://preactjs.com/',
    visible: ref(false),
  },
  {
    name: 'Astro',
    logo: logoAstro,
    color: '#FFFFFF',
    url: 'https://astro.build',
    visible: ref(false),
  },
  {
    name: 'Remix',
    logo: logoRemix,
    color: '#3991fd',
    url: 'https://remix.run/',
    visible: ref(false),
  },
  {
    name: 'Nuxt',
    logo: logoNuxt,
    color: '#00da81',
    url: 'https://nuxt.com',
    visible: ref(false),
  },
  {
    name: 'Qwik',
    logo: logoQwik,
    color: '#18b5f4',
    url: 'https://qwik.dev/',
    visible: ref(false),
  },
  {
    name: 'Redwood',
    logo: logoRedwood,
    color: '#be4622',
    url: 'https://redwoodjs.com/',
    visible: ref(false),
  },
  {
    name: 'Analog',
    logo: logoAnalog,
    color: '#c10f2e',
    url: 'https://analogjs.org/',
    visible: ref(false),
  },
  {
    name: 'Playwright',
    logo: logoPlaywright,
    color: '#d45247',
    url: 'https://playwright.dev/',
    visible: ref(false),
  },
  {
    name: 'Storybook',
    logo: logoStorybook,
    color: '#fd4684',
    url: 'https://storybook.js.org/',
    visible: ref(false),
  },
  {
    name: 'Marko',
    logo: logoMarko,
    color: '#de2a87',
    url: 'https://markojs.com/',
    visible: ref(false),
  },
  {
    name: 'Laravel',
    logo: logoLaravel,
    color: '#eb4432',
    url: 'https://laravel.com/',
    visible: ref(false),
  },
  {
    name: 'AdonisJS',
    logo: logoAdonis,
    color: '#5a45ff',
    url: 'https://adonisjs.com/',
    visible: ref(false),
  },
  {
    name: 'EmberJS',
    logo: logoEmber,
    color: '#e04e39',
    url: 'https://emberjs.com/',
    visible: ref(false),
  },
  {
    name: 'Hono',
    logo: logoHono,
    color: '#ff5c13',
    url: 'https://hono.dev/',
    visible: ref(false),
  },
]

// Starting parameters
const screenWidth: Ref<number> = ref(1920)
let resizeTimeout: ReturnType<typeof setTimeout> | null = null
let timeline: gsap.core.Timeline | null = null

/**
 * When the resize event fires, update the screen width.
 */
const handleResize = () => {
  screenWidth.value = window.innerWidth
}

/**
 * Throttle the resize event handler.
 */
const throttledResizeHandler = () => {
  if (resizeTimeout === null) {
    resizeTimeout = setTimeout(() => {
      handleResize()
      resizeTimeout = null
    }, 100)
  }
}

onMounted(() => {
  // Set the initial size of the screen
  handleResize()

  // Listen for resize events
  window.addEventListener('resize', throttledResizeHandler)

  // Initialize the GSAP timeline
  timeline = gsap.timeline({
    scrollTrigger: {
      trigger: '#frameworks-section',
      start: 'top 70%',
      once: true,
    },
  })

  frameworks.forEach((framework, index) => {
    timeline!.set(framework.visible, { value: true }, index * 0.05)
  })
})

onUnmounted(() => {
  // Deregister the throttled event handler
  window.removeEventListener('resize', throttledResizeHandler)

  // Clear any pending execution of the resize handler
  if (resizeTimeout) {
    clearTimeout(resizeTimeout)
    resizeTimeout = null
  }

  // Kill the GSAP timeline
  if (timeline) {
    timeline.kill()
    timeline = null
  }
})

/**
 * How many total blocks (framework or empty) will fit in a single row?
 */
const numBlocksPerRow: ComputedRef<number> = computed(() => {
  return Math.floor(screenWidth.value / (96 + 24))
})

const paddedBlocksPerSide: ComputedRef<number> = computed(() => {
  if (screenWidth.value < 840) {
    return 0
  }
  if (screenWidth.value < 1280) {
    return 1
  }
  if (screenWidth.value < 1600) {
    return 2
  }
  return Math.max(Math.floor((screenWidth.value - 840) / 280), 0)
})

const numFrameworksPerRow = computed(
  () => numBlocksPerRow.value - paddedBlocksPerSide.value * 2,
)

/**
 * How many rows do we need to display all the frameworks?
 */
const numRows: ComputedRef<number> = computed(() => {
  return Math.ceil(frameworks.length / numFrameworksPerRow.value)
})

/**
 * The indexes of the blocks on each row that support framework cards.
 *
 * Note that the index of the returned array is 1-based.
 */
const centerIndexes: ComputedRef<{ start: number; end: number }[]> = computed(
  () => {
    const firstRowsStartIndex = paddedBlocksPerSide.value
    const frameworksPerFirstRows =
      numBlocksPerRow.value - 2 * paddedBlocksPerSide.value
    const lastRowStartIndex =
      paddedBlocksPerSide.value +
      Math.floor(
        (frameworksPerFirstRows -
          (frameworks.length % frameworksPerFirstRows)) /
          2,
      )
    return new Array(numRows.value + 1).fill(0).map((_, i) => {
      return i < numRows.value ||
        frameworks.length % frameworksPerFirstRows === 0
        ? {
            start: firstRowsStartIndex,
            end: numBlocksPerRow.value - paddedBlocksPerSide.value,
          }
        : {
            start: lastRowStartIndex,
            end:
              lastRowStartIndex +
              (frameworks.length % frameworksPerFirstRows) +
              1,
          }
    })
  },
)

/**
 * Generate CSS transformations for each row, to gracefully slide between horizontal positions.
 */
const rowStyle: ComputedRef<{ transform: string }> = computed(() => {
  return {
    transform: `translate3d(var(--row-offset), 0, 0)`,
  }
})
</script>

<template>
  <section class="frameworks-section" id="frameworks-section">
    <h2>Powering your favorite frameworks and tools</h2>
    <div class="frameworks-container">
      <!-- Top Row -->
      <div class="framework-row" :style="rowStyle">
        <FrameworkCard v-for="_ in numBlocksPerRow + 2" />
      </div>

      <!-- Logo Rows -->
      <template v-for="rowIndex in numRows">
        <div class="framework-row" :style="rowStyle">
          <template v-for="columnIndex in numBlocksPerRow + 2">
            <template
              v-if="
                columnIndex - 1 >= centerIndexes[rowIndex].start &&
                columnIndex - 1 < centerIndexes[rowIndex].end
              "
            >
              <FrameworkCard
                :framework="
                  frameworks[
                    (rowIndex - 1) * numFrameworksPerRow +
                      (columnIndex - 1) -
                      centerIndexes[rowIndex].start
                  ]
                "
              />
            </template>
            <template v-else>
              <FrameworkCard />
            </template>
          </template>
        </div>
      </template>

      <!-- Bottom Row -->
      <div class="framework-row" :style="rowStyle">
        <FrameworkCard v-for="_ in numBlocksPerRow + 2" />
      </div>
    </div>
  </section>
</template>

<style scoped>
.frameworks-section {
  margin-top: 150px;

  @media (min-width: 768px) {
    margin-top: 240px;
  }

  h2 {
    background: linear-gradient(0deg, #fff 0%, rgba(255, 255, 255, 0.76) 100%);
    background-clip: text;
    -webkit-background-clip: text;
    -webkit-text-fill-color: transparent;
    width: 668px;
    max-width: 100%;
    margin: 0 auto;
    text-align: center;
    position: relative;
    z-index: 3;
  }

  .frameworks-container {
    width: 100%;
    background-color: rgba(38, 38, 38, 0.15);
    position: relative;
    margin-top: -20px;
    overflow: hidden;

    @media (min-width: 840px) {
      mask-image: linear-gradient(
        90deg,
        transparent 0%,
        #ffffff 300px,
        #ffffff calc(100vw - 300px),
        transparent 100%
      );
    }

    &:before {
      content: '';
      display: block;
      width: 100%;
      height: 80px;
      background: linear-gradient(
        0deg,
        rgba(23, 23, 23, 0) 0%,
        rgba(16, 16, 16, 0.7) 50%,
        #101010 100%
      );
      position: absolute;
      top: 0;
      left: 0;
      right: 0;
      z-index: 2;
      pointer-events: none;
    }

    &:after {
      content: '';
      display: block;
      width: 100%;
      height: 100px;
      background: linear-gradient(
        180deg,
        rgba(23, 23, 23, 0) 0%,
        rgba(16, 16, 16, 0.7) 50%,
        #101010 100%
      );
      position: absolute;
      bottom: 0;
      left: 0;
      right: 0;
      z-index: 2;
      pointer-events: none;
    }
  }

  .framework-row {
    display: grid;
    grid-auto-columns: 96px;
    grid-gap: 24px;
    justify-content: flex-start;
    margin-bottom: 24px;
    position: relative;
    white-space: nowrap;
    grid-auto-flow: column;

    &:nth-child(even) {
      --row-offset: 36px;
    }

    &:nth-child(odd) {
      --row-offset: 12px;
    }

    @media (min-width: 1080px) {
      &:nth-child(even) {
        --row-offset: 24px;
      }

      &:nth-child(odd) {
        --row-offset: -24px;
      }
    }
  }
}
</style>
